### ISSUE TITLE
TDB - some Station Names are broken

### ISSUE THREAD

**Issue by perpetualKid** [rickloader/NewForestRouteV3#1]
in Watersnake.tdb, there are many station names broken with many hundred empty lines

`PlatformItem (
			TrItemId ( 4405 )
			TrItemSData ( 65 00000002 )
			TrItemRData ( -825.83502 81.249603 26.195272 -6169 14900 )
			PlatformTrItemData ( ffff0000 4404 )
			PlatformName ( "Tcombe West bay" )
			Station ( "TemplecombeGds

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

" )
			PlatformMinWaitingTime ( 60 )
			PlatformNumPassengersWaiting ( 7 )
		)

probably not an issue in normal operations, but breaks tools like TrackViewer and others. Attached is a fixed version, apologize but I'm not cloning a 6GB repository to fix a single file.... 

[Watersnake.zip](https://github.com/rickloader/NewForestRouteV3/files/8475682/Watersnake.zip)

Else looks pretty impressive!

![image](https://user-images.githubusercontent.com/7158903/163033175-0740ff38-a568-4bda-be64-9606e48bcf8e.png)

**Comment by rickloader** [comment]
Thank you very much indeed for noticing  the problem and giving a fix, now applied.
I think he faulty platforms were caused by a bug in TSRE
 all the best Rick
