### ISSUE TITLE
Bad commit.

### ISSUE THREAD

**Issue by djw-zr** [rickloader/NewForestRouteV3#18]
Sorry, I've screwed up.  I found that I did not have permissions to push from my PC directly to your github New Forest Route, but I could use the 'Add file' tab on your main page.  This appeared to work but on checking I found that this has placed all the changed files in your top level directory - and I cannot find a way to revert the commit.

I hope you can sort it out!  D.

**Comment by rickloader** [comment]
Thanks David for correcting these files. Much appreciated. I am not very clear on reverting commits, but.....
Please backup your altered files. Then on Github desktop go to "History" left then right click gets you a menu "amend or revert" Then you can submit again
I think Github wants you to make a fork with your changes and then you merge the fork back into main
I have fetched your commit and I don`t see any changes to NF route. so im not sure where the files are,
If github wont let you do this I will try from my end, once you have the backups, Rick

**Comment by djw-zr** [comment]
I've managed to submit sucessfully from Githib desktop.  I am not sure what RF_DowncastShaft was supposed to represent but someone has been drinking in (the) Bath.  D.
